name: Auto Assign PR Creator as Assignee

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: runner-small
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR creator
        uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
