name: Auto Assign PR Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign author to PR
        # We use the github context directly to ensure the CLI has the right URL
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.event.pull_request.user.login }}" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
